# Generated by Django 3.2 on 2021-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_data_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=50),
        ),
    ]
