# Generated by Django 3.2 on 2021-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_dosier_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=50),
        ),
    ]
