# Generated by Django 3.2 on 2021-05-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dossier_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('military_area', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('start_pose', models.DateField()),
                ('end_pose', models.DateField()),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('school_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=100)),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('number', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dossier')),
            ],
        ),
    ]
